server:
  port: 9000

spring:
  redis:
    host: 106.14.36.107
    port: 6379
    password: 696996
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 1000ms
        max-idle: 200


jwt:
  secret: f4e2e52034348f86b67cde581c0f9eb5
  expire: 3000
  header: token